#!/usr/bin/env python

"""
Add covariate to the phenotypes generated by GCTA. 
Add 1 for CEU samples

Usage: ./add_phenotype_covar.py <labelfile> <phenfile> <adjvalue> > <adjphenfile>
"""

import numpy as np
import pandas as pd
import sys

try:
    labelfile = sys.argv[1]
    phenfile = sys.argv[2]
    adjvalue = float(sys.argv[3])
except:
    sys.stderr.write(__doc__+"\n")
    sys.exit(1)

def AdjustPhenotype(x):
    if x["pop"] == "CEU":
        return x.phen + adjvalue
    else:
        return x.phen

def Standardize(phen):
    m = np.mean(phen)
    s = np.sqrt(np.var(phen))
    return (phen-m)/s

# Read data
labels = pd.read_csv(labelfile, sep="\t", names=["sample", "pop"])
phen = pd.read_csv(phenfile, sep=" ", names=["sample", "fam", "phen","x"])

# Adjust phenotype
phen = pd.merge(phen, labels, on=["sample"])
phen["phen"] = phen.apply(lambda x: AdjustPhenotype(x), 1)

# Standardize
phen["phen"] = Standardize(phen["phen"])

# Output
phen[["sample","fam","phen"]].to_csv(sys.stdout, index=False, sep=" ")
